### ISSUE TITLE
Help Wanted with Calls to SimpleAPI

### ISSUE THREAD

**Issue by jpaulking** [nars1/YottaDB#2]
We have a simple C application prototype which takes input over a (ZeroMQ) TCP socket, interprets incoming data requests, and calls ydb_get_s() or ydb_set_s() as appropriate.

With a one second delay after each call to YottaDB, it works. But if the program returns immediately to the top of the message-reading loop, the call to read the next message fails, citing "Interrupted system call" as the cause.

The error returns if the delay call is placed above the ydb_* call.
The error vanishes if the ydb_* call is omitted.
In all cases ydb_set_s and ydb_get_s return YDB_OK.

We are running YottaDB as built from the simpleapi branch of nars1/YottaDB circa 28 Feb, 2018. We are building and testing primarily on CentOS 7 Linux, with GCC version 5.1, though we have attempted it on a Debian system also and with the same outcome.

A rough pseudo-code outline follows below. In the interest of clarity, I've omitted data transformation, error checking, debug messaging and the like. 

Any thoughts or suggestions would be deeply appreciated.

```

// variable declarations and initializations
int result = ydb_init();
// Check good result or print error message.

while(1)
{
    // This call blocks, waiting on an incoming message.
    // Without the one second delay after the call to ydb_get_s,
    // this call returns an error code and reports 'Interrupted system call'.
    result = zmq_recv(incomingBuffer);
    // Check good result or print last error message.
    
    // Parse the incoming message here and prepare.
    // the needed ydb_buffer_t objects.
    
    result = ydb_get_s(...);
    // Check good result or print error message.
    
    // Delay for one second. With this call in place, the application
    // works, but without it, we see the aforementioned error.
    sleep(1);
    
    // Translate the result to text for the client.
        
    // Reply to the client.
    result = zmq_send(outgoingBuffer);
    // Check good result or print last error message.
}

```

**Comment by nars1** [comment]
ydb_set_s() on a global would start a timer (to flush the dirty database buffers to disk) and that is most likely interrupting the recv() call on the socket.

You need to restart the recv() call in case of EINTR. Like is done in the below file in the YottaDB source repo. There are various other system calls that can get EINTR and need to be handled in the C program by restarting the system call. See eintr_wrappers.h for other such call usages. Hope this helps.

```
sr_port/eintr_wrappers.h
    198 #define RECV(SOCKET, BUF, LEN, FLAGS, RC)                       \
    199 {                                                               \
    200         do                                                      \
    201         {                                                       \
    202                 RC = (int)recv(SOCKET, BUF, (int)(LEN), FLAGS); \
    203         } while (-1 == RC && EINTR == errno);                   \
    204 }
    205 
```

**Comment by jpaulking** [comment]
Thanks for the speedy reply. Very helpful indeed!
